app_1/urls.py
from django.urls import re_path
from .views import index, index_1
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^halaman', index_1, name='index_1'),

]

lab_1/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import re_path, path
from app_1.views import index as index_lab1
from app_1.views import index_1 as index_lab3
from lab_6.views import form1 as form1
from lab_6.views import saveForm1
from lab_6.views import saveForm2
from lab_6.views import form2 as form2
from lab_6.views import daftarKegiatan as daftarKegiatan



urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path(r'^lab_1', index_lab1, name='index'),
    re_path(r'^halaman', index_lab3, name='index'),
    re_path('', include('lab_4.urls')),
    re_path(r'^formulir1', form1, name='form1'),
    re_path('saveForm1', saveForm1),
    re_path(r'^formulir2', form2, name='form2'),
    re_path('saveForm2', saveForm2),
    re_path(r'^daftarKegiatan', daftarKegiatan, name='daftarKegiatan'),
    re_path('', include('lab_8.urls')),
    re_path('', include('account.urls')), 
]

lab_6/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

class Formulir_pertama(models.Model):
    name = models.CharField(max_length=60)
    email = models.CharField(max_length=60)
    
# Create your models here.
class Formulir_kedua(models.Model):
    name = models.CharField(max_length=60)
    email = models.CharField(max_length=60)

lab_6/forms.py
from django import forms
from .models import Formulir_pertama, Formulir_kedua

class Input_Form(forms.ModelForm):
	class Meta:
		model = Formulir_pertama
		fields = ['name','email']
		error_messages = {
			'required' : 'Please Type'
		}
	name = forms.CharField(label='', required=False, max_length=60)
	email = forms.CharField(label='', required=False, max_length=60)


class Input_Form2(forms.ModelForm):
	class Meta:
		model = Formulir_kedua
		fields = ['name','email']
		error_messages = {
			'required' : 'Please Type'
		}
	name = forms.CharField(label='', required=False, max_length=60)
	email = forms.CharField(label='', required=False, max_length=60)


	

lab_6/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Input_Form, Input_Form2
from .models import Formulir_pertama, Formulir_kedua
from django.contrib.auth.decorators import login_required

# Create your views here.
# @login_required(login_url='/login')
def form1(request):
	if request.user.is_authenticated:
		user = request.session['user_login']
		response = {'author' : user}
	else:
		response = {'author' : ' '}
	return render(request, 'main/formulir1.html', response)

# @login_required(login_url='/login')
def saveForm1(request):
	form = Input_Form(request.POST)

	if form.is_valid():
		print("bisa")
		if request.method == 'POST':
				form.save()
				return HttpResponseRedirect('/daftarKegiatan')

# @login_required(login_url='/login')
def form2(request):
	if request.user.is_authenticated:
		user = request.session['user_login']
		response = {'author' : user}
	else:
		response = {'author' : ' '}
	return render(request, 'main/formulir2.html', response)

# @login_required(login_url='/login')
def saveForm2(request):
	form = Input_Form2(request.POST)
	if form.is_valid():
		if request.method == 'POST':
				form.save()
				return HttpResponseRedirect('/daftarKegiatan')

# @login_required(login_url='/login')
def daftarKegiatan(request):
	form1 = Formulir_pertama.objects.all()
	form2 = Formulir_kedua.objects.all()
	if request.user.is_authenticated:
		user = request.session['user_login']
		response = {'author' : user, 'forms1' : form1, 'forms2' : form2}
	else:
		response = {'author' : ' '}
	return render(request, 'main/daftarKegiatan.html', response)

lab_6/templates/main/daftarKegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Daftar Kegiatan Randa Story 6</title>
{% endblock meta %}

{% block content %}
  <section id="">
		<div class="container">
			<div class="card col-md-6" style="text-align: center">
				<h1>Daftar Kegiatan</h1>
			</div>
		<div class="card col-md-6 dibawah" >
			<h3>Diskusi <i>Front End</i></h3><br>
			<div style="overflow-x:auto;">
			<table class="table" id="myTable">
	    		
	    		<thead >
	    		<tr>
	    			<th>Nama</th>
	    			<th>Email</th>
	    			
	    		</tr>
	    		</thead>
			{% if forms1 %}
			<tbody>
				{% for data in forms1 %}
		
				<tr>
					<td>{{ data.name }}</td>
					<td>{{ data.email }}</td>	
				</tr>
				
		<br/>
		{% endfor %}
		</tbody>
	{% endif %}
</table>
</div>
<div class="tombol" style="margin-top: 20px !important"><a id="link" href="{% url 'form1' %}">Ikut Kegiatan</a></div>
	    </div>
	    <div class="card col-md-6 dibawah" >
			<h3>Diskusi Django</h3><br>
			<div style="overflow-x:auto;">
			<table class="table" id="myTable">
	    		
	    		<thead >
	    		<tr>
	    			<th>Nama</th>
	    			<th>Email</th>
	    			
	    		</tr>
	    		</thead>
			{% if forms2 %}
			<tbody>
				{% for data in forms2 %}
		
				<tr>
					<td>{{ data.name }}</td>
					<td>{{ data.email }}</td>	
				</tr>
				
		<br/>
		{% endfor %}
		</tbody>
	{% endif %}
	
</table>
</div>
<div class="tombol" style="margin-top: 20px !important"><a id="link" href="{% url 'form2' %}">Ikut Kegiatan</a></div>
	    </div>

	</div>
<br>
	</section>

	<style type="text/css">
		.container {
			font-size: 15px;
			margin-bottom: 100px;

		}
		.card {
			margin-left: 23%;
			margin-right: 23%;
		}
		.dibawah {
			margin-top: 50px !important;
		}
		#link { 
			background-color: #EEF8FF;
			color: black;
			box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
			padding: 10px 10px 10px 10px;
			border-radius: 5px;
			margin-bottom: 10px;

		}


		#link:hover {
			text-decoration: none;
			color: white;
			background-color: #78E3FD;
		}
		.tombol {
			margin-bottom: 20px;
		}

		table {
  border-collapse: collapse;
  border-spacing: 0;
  width: 100%;
  border: 1px solid #ddd;
}

th, td {
  text-align: left;
  padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

	</style>
	
{% endblock content %}

lab_6/templates/main/formulir1.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 6 Randa Formulir Kegiatan 1</title>
{% endblock meta %}

{% block content %}
  <section id="">
		<div class="container">
		<div class="card col-md-6">
			<h3>Kegiatan 1</h3><br>
			<h3>Silakan Masukan Data Diri</h3><br>
			<form action="saveForm1" method="POST">
				{% csrf_token %}
				<input type="text" name="name" placeholder="Nama" maxlength="60" id="id_name" required><br><br>
				<input type="text" name="email" placeholder="Email" maxlength="60" id="id_email" required><br><br>
				<input id="submit" type="submit" value="Submit">
			</form>
	    </div>

	</div>
<br>
	</section>

	<style type="text/css">
		input {
			padding: 5px 5px 5px 5px;
			border-radius: 10px;
			border-width: 1px;
			width: 100%;
			border-color: white;
		}
		.container {
			font-size: 15px;
			margin-bottom: 100px;

		}
		#submit {
			width: 30%;
			background-color: #34F6F2;
			color: white;
			font-weight: bold;
		}
		#submit:hover {
			width: 30%;
			
			background-color: #07A3D5;
			color: white;
			font-weight: bold;
		}
		.card {
			margin-left: 23%;
			margin-right: 23%;
		}
	</style>
	
{% endblock content %}

lab_6/templates/main/formulir2.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 6 Randa Formulir Kegiatan 2</title>
{% endblock meta %}

{% block content %}
  <section id="">
		<div class="container">
		<div class="card col-md-6">
			<h3>Kegiatan 2</h3><br>
			<h3>Silakan Masukan Data Diri</h3><br>
			<form action="saveForm2" method="POST">
				{% csrf_token %}
				<input type="text" name="name" placeholder="Nama" maxlength="60" id="id_name" required><br><br>
				<input type="text" name="email" placeholder="Email" maxlength="60" id="id_email" required><br><br>
				<input id="submit" type="submit" value="Submit">
			</form>
	    </div>

	</div>
<br>
	</section>

	<style type="text/css">
		input {
			padding: 5px 5px 5px 5px;
			border-radius: 10px;
			border-width: 1px;
			width: 100%;
			border-color: white;
		}
		.container {
			font-size: 15px;
			margin-bottom: 100px;

		}
		#submit {
			width: 30%;
			background-color: #34F6F2;
			color: white;
			font-weight: bold;
		}
		#submit:hover {
			width: 30%;
			
			background-color: #07A3D5;
			color: white;
			font-weight: bold;
		}
		.card {
			margin-left: 23%;
			margin-right: 23%;
		}
	</style>
	
{% endblock content %}