account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register', views.registerPage, name='register'),
    path('login', views.loginPage, name='login'),
    path('logout', views.logoutUser, name='logout'),
]

app_1/urls.py
from django.urls import re_path
from .views import index, index_1
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^halaman', index_1, name='index_1'),

]

lab_1/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import re_path, path
from app_1.views import index as index_lab1
from app_1.views import index_1 as index_lab3
from lab_6.views import form1 as form1
from lab_6.views import saveForm1
from lab_6.views import saveForm2
from lab_6.views import form2 as form2
from lab_6.views import daftarKegiatan as daftarKegiatan



urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path(r'^lab_1', index_lab1, name='index'),
    re_path(r'^halaman', index_lab3, name='index'),
    re_path('', include('lab_4.urls')),
    re_path(r'^formulir1', form1, name='form1'),
    re_path('saveForm1', saveForm1),
    re_path(r'^formulir2', form2, name='form2'),
    re_path('saveForm2', saveForm2),
    re_path(r'^daftarKegiatan', daftarKegiatan, name='daftarKegiatan'),
    re_path('', include('lab_8.urls')),
    re_path('', include('account.urls')), 
]

lab_4/urls.py
from django.urls import re_path

from . import views

app_name = 'lab_4'

urlpatterns = [
    re_path(r'^$', views.home, name='home'),
    re_path(r'^pendidikan', views.pendidikan, name='pendidikan'),
    re_path(r'^matkul', views.matkul, name='matkul'),
    re_path('savematkul', views.savematkul),
    re_path('readmatkul', views.readmatkul, name='readmatkul'),
    re_path(r'^delete/(?P<data>[-\w]+)/$',views.delete, ),
    re_path(r'^detail/(?P<data>[-\w]+)/$', views.readmatkulDetail, ),
]

lab_8/urls.py
from django.urls import re_path
from . import views

app_name = 'lab_8'

urlpatterns = [
    re_path(r'^buku', views.buku, name='buku'),
    re_path('data', views.daftar_buku),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="{{author}}">
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,900' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Cardo:100,200,300,400,500,600,700,900' rel='stylesheet'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/newStyle2.css' %}">
    <style type="text/css">
      body {
        font-size: 15px;
      }
      a {
        font-size: 15px;
      }
      .myPage {
        padding: 14px 16px;
      }

      .links {
        padding: 14px 16px;
        font-size: 15px;
      }
      #logout {
        color: red;
        font-weight: bold;
      }
      .glyphicon{
        margin-right: 5px; 
      }
    </style>
    
  {% block meta %}
  {% endblock meta %}
</head>

<body>
<!--<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<ul id="myDIV">
  <li class="myPage">My Page</li>
 <li class="links"><a class="bton" href="#kontak">Kontak</a></li>
  <li class="links"><a class="bton" href="#minat">Minat</a></li>
  <li class="links"><a class="bton" href="#pengalaman">Pengalaman</a></li>-->
  <!--
  <li><a class="bton" href="{% url 'lab_8:buku' %}">Daftar Buku</a></li>
  <li><a class="bton" href="{% url 'daftarKegiatan' %}">Kegiatan</a></li>
  <li><a class="bton" href="{% url 'lab_4:readmatkul' %}">Mata Kuliah</a></li>
  <li class="links"><a class="bton" href="{% url 'lab_4:pendidikan' %}">Pendidikan</a></li>-->
 <!-- <li><a class="bton" href="{% url 'lab_4:home' %}">Beranda</a></li>
  
</ul>
<span><a href="{% url 'account:logout' %}">Logout</a></span>
  <span>Hello, {{request.user}}</span>
</nav>-->

<nav class="navbar">
 <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" style="background-color: rgba(2,0,36,1)" data-toggle="collapse" data-target="#ahaha">
        <span style="background-color: white" class="sr-only">Toggle navigation</span>
        <span style="background-color: white" class="icon-bar"></span>
        <span style="background-color: white" class="icon-bar"></span>
        <span style="background-color: white" class="icon-bar"></span>
      </button>
    </div>
  <div class="collapse navbar-collapse" id="ahaha">
    <ul class="navbar-nav">
      <li class="myPage" style="margin-right: 100px; margin-left: 50px;">My Page</li>
      {% if user.is_authenticated %}
      <li class="">
        <a class="" href="{% url 'lab_4:home' %}">Beranda</a>
      </li>
      <li class="">
        <a class="" href="{% url 'lab_4:readmatkul' %}">Mata Kuliah</a>
      </li>
      <li class="">
        <a class="" href="{% url 'daftarKegiatan' %}">Kegiatan</a>
      </li>
      <li class="">
        <a class="" href="{% url 'lab_8:buku' %}">Daftar Buku</a>
      </li>
      {% endif %}
      {% if user.is_authenticated %}
       <span><a  class="links" id="logout" href="{% url 'account:logout' %}"><span class="glyphicon glyphicon-log-in"></span>Logout</a></span>
       <span class="links" style=""><span class="glyphicon glyphicon-user"></span>Hello, {{author}}</span>
       {% else %}
       <span><a  class="links" href="{% url 'account:login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a></span>
       <span><a  class="links" href="{% url 'account:register' %}"><span class="glyphicon glyphicon-user"></span>Signup {{author}}</a></span>
       {% endif %}
  
    </ul>
    
  </div>
</div>
  
   

  

</nav>


{% block content %}
  {% endblock content %}

<footer>
	<div class="footer">
  <p>© 2020 Randa Alfarisyi</p>
</div>
</footer>
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" crossorigin="anonymous"></script>
<script>
for (var i = 0; i < document.links.length; i++) {
    if (document.links[i].href == document.URL) {
        document.links[i].className = 'active';
    }
}
</script>
</body>
  
</html>